# Copyright (c) 2022-2026, PostgreSQL Global Development Group

# Randomized single-session stress test for global temporary tables.
#
# A GTT and a local temporary table receive identical streams of randomly
# generated DML (inserts with ON CONFLICT -- explicit-id and
# identity-assigned -- toasted-text writes, updates, deletes, TRUNCATE with
# and without RESTART IDENTITY) at random savepoint depths, with random
# ROLLBACK TO / RELEASE / top-level commit-or-rollback outcomes, occasional
# in-transaction index and column DDL, and periodic DISCARD TEMP.  The local
# temp table goes through the ordinary transactional storage machinery and
# therefore serves as an oracle: after every top-level transaction the two
# tables must have identical contents, both via a plain scan and via a
# forced index scan, and amcheck must pass on the GTT's primary key
# (heapallindexed included), validating the btree structure against the
# heap.  A second ON COMMIT DELETE ROWS pair covers the commit-truncation
# machinery; an identity column covers per-session GTT sequences (which the
# RESTART IDENTITY and DISCARD paths reset on both sides identically); a
# text column exercises the toast lifecycle.  Periodic reconnects exercise
# the lazy fresh-session paths and backend-exit cleanup.
#
# The run is seeded so failures replay: set GTT_STRESS_SEED to the seed
# reported by a failing run.  GTT_STRESS_XACTS (default 100) scales the run
# length.

use strict;
use warnings FATAL => 'all';

use PostgreSQL::Test::Cluster;
use PostgreSQL::Test::Utils;
use Test::More;

my $nxacts = $ENV{GTT_STRESS_XACTS} || 100;
my $seed =
  defined $ENV{GTT_STRESS_SEED}
  ? $ENV{GTT_STRESS_SEED}
  : int(rand(1 << 30));
srand($seed);
diag("gtt stress: seed=$seed transactions=$nxacts");

my $node = PostgreSQL::Test::Cluster->new('gtt_stress');
$node->init;
$node->start;

$node->safe_psql(
	'postgres', q{
	CREATE EXTENSION amcheck;
	CREATE GLOBAL TEMPORARY TABLE gtt_s
		(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		 v int, t text);
	CREATE GLOBAL TEMPORARY TABLE gtt_ocdr_s (x int) ON COMMIT DELETE ROWS;
});

# A deterministic ~2.5kB incompressible-ish text expression, parameterized
# by the row counter so both tables compute the same value: large enough to
# be toasted, exercising the toast lifecycle under the savepoint churn.
sub bigtext
{
	return
	  "(SELECT string_agg(md5((i * 97 + j)::text), '') FROM generate_series(1, 80) j)";
}

# The session under test.  The local temp oracles are per-session, so they
# are recreated on every reconnect (and after DISCARD TEMP); the GTT
# definitions persist and their data starts empty, matching fresh oracles.
my $s;

sub create_oracles
{
	$s->query_safe(
		q{CREATE TEMP TABLE ora_s
			(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			 v int, t text);
		  CREATE TEMP TABLE ora_ocdr_s (x int) ON COMMIT DELETE ROWS;});
	return;
}

sub fresh_session
{
	$s->quit if defined $s;
	$s = $node->background_psql('postgres');
	# IF [NOT] EXISTS notices would otherwise trip query_safe
	$s->query_safe('SET client_min_messages = warning;');
	create_oracles();
	return;
}

fresh_session();

# Statement log of the current transaction, for replay diagnostics.
my @xlog;

sub run_sql
{
	my $sql = shift;
	push @xlog, $sql;
	$s->query_safe($sql);
	return;
}

# Apply the same statement shape to a GTT and its oracle.
sub run_both
{
	my $fmt = shift;
	run_sql(sprintf($fmt, 'gtt_s') . ' ' . sprintf($fmt, 'ora_s'));
	return;
}

my $spcount = 0;
my $bad = 0;

my $contents_sql =
  q{coalesce(string_agg(id || ':' || v || ':' || coalesce(md5(t), '-'), ',' ORDER BY id), '')};

sub report_mismatch
{
	my $why = shift;
	my $gtt = $s->query_safe("SELECT $contents_sql FROM gtt_s");
	my $ora = $s->query_safe("SELECT $contents_sql FROM ora_s");
	diag("MISMATCH ($why) at seed=$seed");
	diag("transaction statements:\n" . join("\n", @xlog));
	diag("gtt_s:  $gtt");
	diag("ora_s:  $ora");
	$bad = 1;
	return;
}

for my $x (1 .. $nxacts)
{
	# Reconnect periodically: fresh lazy state against the same definition.
	fresh_session() if $x % 25 == 0;

	@xlog = ();
	my @sps = ();

	eval {
		run_sql('BEGIN;');
		my $nops = 1 + int(rand(10));
		for (1 .. $nops)
		{
			my $r = rand();
			my $a = 1 + int(rand(100));
			my $b = $a + int(rand(20));
			if ($r < 0.22)
			{
				run_both(
					"INSERT INTO %s (id, v) SELECT i, i / 3 FROM generate_series($a, $b) i ON CONFLICT (id) DO NOTHING;"
				);
			}
			elsif ($r < 0.30)
			{
				# identity-assigned ids: both sequences see the same stream
				run_both(
					"INSERT INTO %s (v) SELECT i FROM generate_series(1, @{[ 1 + int(rand(5)) ]}) i ON CONFLICT (id) DO NOTHING;"
				);
			}
			elsif ($r < 0.36)
			{
				# toasted text payload
				run_both(
					"INSERT INTO %s (id, v, t) SELECT i, 0, @{[ bigtext() ]} FROM generate_series($a, $b) i ON CONFLICT (id) DO NOTHING;"
				);
			}
			elsif ($r < 0.46)
			{
				run_both(
					rand() < 0.5
					? "UPDATE %s SET v = v + 1 WHERE id BETWEEN $a AND $b;"
					: "UPDATE %s SET t = left(coalesce(t, '') || md5(id::text), 4000) WHERE id BETWEEN $a AND $b;"
				);
			}
			elsif ($r < 0.56)
			{
				run_both("DELETE FROM %s WHERE id BETWEEN $a AND $b;");
			}
			elsif ($r < 0.61)
			{
				run_both(
					rand() < 0.5
					? "TRUNCATE %s;"
					: "TRUNCATE %s RESTART IDENTITY;");
			}
			elsif ($r < 0.66)
			{
				run_sql(
					"INSERT INTO gtt_ocdr_s SELECT g FROM generate_series(1, 5) g; "
					  . "INSERT INTO ora_ocdr_s SELECT g FROM generate_series(1, 5) g;"
				);
			}
			elsif ($r < 0.76)
			{
				$spcount++;
				push @sps, "sp$spcount";
				run_sql("SAVEPOINT sp$spcount;");
			}
			elsif ($r < 0.85 && @sps)
			{
				my $k = int(rand(scalar(@sps)));
				run_sql("ROLLBACK TO SAVEPOINT $sps[$k];");
				@sps = @sps[ 0 .. $k ];
			}
			elsif ($r < 0.90 && @sps)
			{
				my $k = int(rand(scalar(@sps)));
				run_sql("RELEASE SAVEPOINT $sps[$k];");
				@sps = $k > 0 ? @sps[ 0 .. $k - 1 ] : ();
			}
			elsif ($r < 0.94)
			{
				# In-transaction index DDL on the GTT only; IF [NOT] EXISTS
				# keeps this oblivious to surrounding subxact rollbacks.
				run_sql(
					rand() < 0.5
					? 'CREATE INDEX IF NOT EXISTS gtt_s_v_idx ON gtt_s (v);'
					: 'DROP INDEX IF EXISTS gtt_s_v_idx;');
			}
			elsif ($r < 0.97)
			{
				# column DDL: same shape on both tables so contents compare
				run_both(
					rand() < 0.5
					? "ALTER TABLE %s ADD COLUMN IF NOT EXISTS extra int DEFAULT 0;"
					: "ALTER TABLE %s DROP COLUMN IF EXISTS extra;");
			}
			else
			{
				my $same = $s->query_safe(
					'SELECT (SELECT count(*) FROM gtt_s) = (SELECT count(*) FROM ora_s);'
				);
				if ($same ne 't')
				{
					report_mismatch("mid-transaction count, xact $x");
					last;
				}
			}
		}
		run_sql(rand() < 0.7 ? 'COMMIT;' : 'ROLLBACK;');
	};
	if ($@)
	{
		diag("ERROR at seed=$seed, xact $x: $@");
		diag("transaction statements:\n" . join("\n", @xlog));
		$bad = 1;
	}
	last if $bad;

	# Full-content verification through the default (sequential) path.
	my $same = $s->query_safe(
		"SELECT (SELECT $contents_sql FROM gtt_s) = (SELECT $contents_sql FROM ora_s);"
	);
	if ($same ne 't')
	{
		report_mismatch("post-transaction contents, xact $x");
		last;
	}

	# The ON COMMIT DELETE ROWS pair must agree too (both empty after any
	# top-level transaction end).
	$same = $s->query_safe(
		'SELECT (SELECT count(*) FROM gtt_ocdr_s) = (SELECT count(*) FROM ora_ocdr_s)
		    AND (SELECT count(*) FROM gtt_ocdr_s) = 0;');
	if ($same ne 't')
	{
		report_mismatch("ON COMMIT DELETE ROWS state, xact $x");
		last;
	}

	# Range probe through a forced index scan: catches index entries whose
	# TIDs do not correspond to live oracle-confirmed heap data.
	my $a = 1 + int(rand(100));
	my $b = $a + int(rand(30));
	$s->query_safe('SET enable_seqscan = off; SET enable_bitmapscan = off;');
	$same = $s->query_safe(
		"SELECT (SELECT count(*) FROM gtt_s WHERE id BETWEEN $a AND $b)
		      = (SELECT count(*) FROM ora_s WHERE id BETWEEN $a AND $b);");
	$s->query_safe('RESET enable_seqscan; RESET enable_bitmapscan;');
	if ($same ne 't')
	{
		report_mismatch("forced index scan BETWEEN $a AND $b, xact $x");
		last;
	}

	# Structural verification: the probe above built the pkey if it wasn't
	# already, so amcheck can read it; heapallindexed additionally proves
	# heap and index agree.
	if (rand() < 0.30)
	{
		my $heapallindexed = rand() < 0.5 ? 'true' : 'false';
		$s->query_safe(
			"SELECT bt_index_check('gtt_s_pkey', $heapallindexed);");
	}

	# Occasional maintenance commands; they must not change contents.  Use
	# VACUUM (ANALYZE) rather than bare VACUUM: when the session has no data
	# the latter emits an INFO, which ignores client_min_messages and would
	# trip query_safe.
	if (rand() < 0.15)
	{
		$s->query_safe(
			rand() < 0.5 ? 'VACUUM (ANALYZE) gtt_s;' : 'ANALYZE gtt_s;');
	}

	# Occasionally release everything: DISCARD TEMP dematerializes the GTT
	# session data (and identity sequence) and drops the temp oracles; both
	# sides then restart from the same empty state.
	if (rand() < 0.05)
	{
		$s->query_safe('DISCARD TEMP;');
		my $empty = $s->query_safe(
			'SELECT (SELECT count(*) FROM gtt_s) = 0
			    AND (SELECT count(*) FROM gtt_ocdr_s) = 0;');
		if ($empty ne 't')
		{
			diag("DISCARD TEMP left data behind at seed=$seed, xact $x");
			$bad = 1;
			last;
		}
		create_oracles();
	}
}

ok(!$bad, "$nxacts random transactions matched the oracle (seed $seed)");

$s->quit;

# A peer session must be able to drop the tables once the stress session is
# gone: no stale registry entry or session file may survive.
$s = undef;
$node->safe_psql('postgres', 'DROP TABLE gtt_s; DROP TABLE gtt_ocdr_s;');
pass('DROP TABLE succeeds after the stress session disconnected');

$node->stop;
done_testing();
